// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using User.Infrastructure.Persistence.Read.Context;

namespace User.Infrastructure.Persistence.Read.Migrations
{
    [DbContext(typeof(UserReadModelContext))]
    partial class UserReadModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("User.Infrastructure.Persistence.Read.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("MailAddress")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("Users", "UserRead");
                });
#pragma warning restore 612, 618
        }
    }
}
